### PR TITLE
Not throughly necessary PR

### PR DESCRIPTION
**Pull request by pedrocamargo**
Ben,
          I was loading all these networks in order to test AequilibraE's upcoming equilibrium assignments and I faced an issue with the consistency of the files, as they would load completely different in Pandas, so I edited as little as possible some of the files in order to get them all to be a little more consistent with each other.

Feel free to deny the merge if you think that there is no value to such change.

### CODE REVIEW

**Comment by bstabler** [comment]
the purpose is for consistent formatting for reading into pandas?  Can you include the pandas script as well?  It might be useful to others.

**Comment by pedrocamargo** [comment]
I'll clean the code (for both networks and matrices) and submit that as well

**Comment by chkwon** [comment]
The pandas script would be awesome. I can probably work on a julia version following Pedro's.

**Comment by pedrocamargo** [comment]
Done, @bstabler 
I have added a script to import matrices into OMX and made all the network files consistent with each other.

The Jupyter notebook I added there also has a few lines on importing the network into Pandas, as it is really simple.

**Comment by bstabler** [comment]
@pedrocamargo do you want to update the readme as well to mention the script?

**Pull request merged**
